version: "3"

services:
  admin-ui:
    image: drill4j/admin-ui
    ports:
      - 3000:8080
    environment:
      - REACT_APP_API_HOST=drill-admin:8090
  admin:
    image: drill4j/admin
    hostname: drill-admin
    ports:
      - 8090:8090
