version: "3"

services:
  admin-ui:
    # it's a lates version of drill ui
    image: drill4j/admin-ui
    # To find the version you need, follow the link  https://hub.docker.com/r/drill4j/admin-ui/tags
    ports:
      - 3000:8080
    environment:
      - REACT_APP_API_HOST=drill-admin:8090
  admin:
    # it's a lates version of drill backend
    image: drill4j/admin
    # To find the version you need, follow the link  https://hub.docker.com/r/drill4j/admin/tags
    hostname: drill-admin
    ports:
      - 8090:8090
